[build]
command = "make production-build"
publish = "public"

[build.environment]
HUGO_VERSION = "0.93.2"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"
